### ISSUE TITLE
new README

### ISSUE THREAD

**Issue by KILowrey** [n-lambert/Inn-At-The-Edge-of-Copyright#126]
a new carefully constructed readme to weather any storm

**Comment by ajlb** [comment]
moving this out of code review until you have an open pull request - 
I say yoink the License text and just link to it like you suggested previously 
then swap the logo for the one you asked Talia for today (black on white instead of white on black)
reference ingame names on contributors:

- [ ] Bismuth the KILer (Kira)
- [ ] Chordori (Plover)
- [ ] Cosmo The Magnificent (Nancy)
- [ ] Mandolorian (Armando)
- [ ] Shambles (Nick)
- [ ] Quill (Talia)
- [ ] 6One9 (Jeneth)

otherwise looks good
